dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  evm_version: london
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
    version: 0.8.16
    optimizer:
      enabled: true
      runs: 20000
